version: '3.9'

services:
  front:
    build:
      context: .
      dockerfile: ./infra/front/Dockerfile
    working_dir: /usr/src/front
    volumes:
      - ./front:/usr/src/front
    ports:
      - "3000:3000"
    tty: true